routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::resource('posts',PostController::class)
->only(['index','create','store','edit','update','destroy','show'])
->middleware(['auth','verified']);

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use App\Events\PostCreated;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable = [
      'title',
      'post_content',
      'image',
    ];
    public function user()
    {
        return $this->belongsTo(User::class);
    }
    protected $dispatchesEvents = [
        'created' => PostCreated::class,
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function posts() {
      return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Str;



class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('posts.index',[
        'posts' => Post::with('user')
          ->latest()
          ->get(),
      ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $validated = $request->validate([
        'post_content' => 'required|string',
        'title' => 'required|string|max:255',
        'image' => 'required|mimes:jpg,png,jpeg|max:5048',
      ]);

      $newImageName = uniqid() . '-' . Str::slug($request->title) . '.' .$request->image->extension(); 
      $request->image->move(public_path('images'), $newImageName);
      $validated['image'] = 'images/'.$newImageName;  
      $request->user()->posts()->create($validated);
      

      return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
      return view('posts.show',[
        'post' => $post,
      ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
      return view('posts.edit',[
        'post' => $post,
      ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $this->authorize('update', $post);
        $validated = $request->validate([
          'post_content' => 'required|string',
          'title' => 'required|string|max:255',
          'image' => 'required|mimes:jpg,png,jpeg|max:5048',
        ]);
        $newImageName = uniqid() . '-' . Str::slug($request->title) . '.' .$request->image->extension(); 
        $request->image->move(public_path('images'), $newImageName);
        $validated['image'] = 'images/'.$newImageName; 
        $post->update($validated);
 
        return redirect(route('posts.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
      $this->authorize('delete', $post);
 
        $post->delete();
 
        return redirect(route('posts.index'));
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): View
    {
        return view('profile.edit', [
            'user' => $request->user(),
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('profile.edit')->with('status', 'profile-updated');
    }

    /**
     * Delete the user's account.
     */
    public function destroy(Request $request): RedirectResponse
    {
        $request->validateWithBag('userDeletion', [
            'password' => ['required', 'current-password'],
        ]);

        $user = $request->user();

        Auth::logout();

        $user->delete();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return Redirect::to('/');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 text-gray-900">
                    {{ __("You're logged in!") }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans text-gray-900 antialiased">
        <div class="min-h-screen flex flex-col sm:justify-center items-center pt-6 sm:pt-0 bg-gray-100">
            <div>
                <a href="/">
                    <x-application-logo class="w-20 h-20 fill-current text-gray-500" />
                </a>
            </div>

            <div class="w-full sm:max-w-md mt-6 px-6 py-4 bg-white shadow-md overflow-hidden sm:rounded-lg">
                {{ $slot }}
            </div>
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-9 w-auto fill-current text-gray-800" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
                        {{ __('Posts') }}
                    </x-nav-link>
                    <x-nav-link :href="route('posts.create')" :active="request()->routeIs('posts.create')">
                        {{ __('Create post') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <x-dropdown-link :href="route('profile.edit')">
                            {{ __('Profile') }}
                        </x-dropdown-link>

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
      <x-responsive-nav-link :href="route('posts.index')" :active="request()->routeIs('posts.index')">
        {{ __('Posts') }}
      </x-responsive-nav-link>
      <x-responsive-nav-link :href="route('posts.create')" :active="request()->routeIs('posts.create')">
          {{ __('Create post') }}
      </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <x-responsive-nav-link :href="route('profile.edit')">
                    {{ __('Profile') }}
                </x-responsive-nav-link>

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/posts/create.blade.php
<x-app-layout>
  
 <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
    <h1 class="text-gray-700 font-bold text-2xl my-4">{{ __('Add a new post') }}</h1>
    <form method="POST" action="{{ route('posts.store') }}" enctype="multipart/form-data">
      @csrf
      <input 
        type="text"
        name="title"
        class="p-2 border-gray-300 rounded-md my-4 w-full outline-none focus:border-blue-300 transition duration-300" 
        placeholder="Title"
        value="{{ old('title') }}"
      />
      <x-input-error :messages="$errors->get('title')" class="my-2"/>
      <textarea 
        name="post_content"
        placeholder="What's looking for !.."
        class="h-40 max-w-full w-full border-gray-300 focus:border-blue-300 outline-none rounded-md transition duration-300 focus:border-2 focus:shadow focus:shadow-blue-200"
      >{{ old('post-content') }}</textarea>
      <x-input-error :messages="$errors->get('post-content')" class="mt-2"/>
      <div class="w-full bg-gray-400 flex justify-center items-center h-10 my-4 rounded-md hover:bg-blue-500 transition duration-500">
          <label for="dropzone-file" class="font-semibold cursor-pointer text-gray-100">Click to upload</label>
          <input name="image" id="dropzone-file" type="file" class="hidden" />
      </div>
      <x-input-error :messages="$errors->get('image')" class="my-2"/>
      <button class="text-gray-100 px-4 py-2 bg-blue-500 font-bold rounded-md hover:bg-blue-700 transition duration-400 mt-4" type="submit">Post</button>
  </form>
  </div>
</x-app-layout>

resources/views/posts/edit.blade.php
<x-app-layout>
  
 <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
    <h1 class="text-gray-700 font-bold text-2xl my-4">{{ __('Edit post') }}</h1>
    <form method="POST" action="{{ route('posts.update',$post) }}" enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <input 
        type="text"
        name="title"
        class="p-2 border-gray-300 rounded-md my-4 w-full outline-none focus:border-blue-300 transition duration-300" 
        placeholder="Title"
        value="{{ $post->title }}"
      />
      <x-input-error :messages="$errors->get('title')" class="my-2"/>
      <textarea 
        name="post_content"
        placeholder="What's looking for !.."
        class="h-40 max-w-full w-full border-gray-300 focus:border-blue-300 outline-none rounded-md transition duration-300 focus:border-2 focus:shadow focus:shadow-blue-200"
      >{{ $post->post_content }}</textarea>
      <x-input-error :messages="$errors->get('post-content')" class="mt-2"/>
      <div class="w-full bg-gray-400 flex justify-center items-center h-10 my-4 rounded-md hover:bg-blue-500 transition duration-500">
          <label for="dropzone-file" class="font-semibold cursor-pointer text-gray-100">Click to upload</label>
          <input name="image" id="dropzone-file" type="file" class="hidden" value="{{ $post->image }}" />
      </div>
      <x-input-error :messages="$errors->get('image')" class="my-2"/>
      <button class="text-gray-100 px-4 py-2 bg-blue-500 font-bold rounded-md hover:bg-blue-700 transition duration-400 mt-4" type="submit">Edit</button>
  </form>
  </div>
</x-app-layout>

resources/views/posts/index.blade.php
<x-app-layout>
  
 <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
    <h1 class="text-gray-700 font-bold text-2xl my-4">{{ __('All Posts') }}</h1>
    @foreach ($posts as $post) 
    <div class="flex gap-5 w-full p-2 my-4 bg-white h-max rounded-md">
      <div class="flex w-1/3">
        <img class="rounded-tl-md rounded-bl-md object-cover w-full h-full" src="{{ $post->image }}" alt="{{ $post->title }}"/>
      </div>
      <div class="w-2/3 relative">
        <div>
          <h1 class="text-gray-800 text-2xl font-bold mb-2 justify-start">{{ $post->title }}</h1>
          <div>
            <span class="text-gray-600">{{ $post->user->name }}</span>
            <small class="ml-2 text-xs text-gray-600">{{ $post->created_at->format('j M Y, g:i a') }}</small>
            @unless ($post->created_at->eq($post->updated_at))
            <small class="text-sm text-gray-600"> &middot; {{ __('edited') }}</small>
            @endunless
          </div>
        </div>
        <p class="text-gray-700 leading-6 justify-self-center mb-12">
          {{ $post->post_content }}
        </p>
        <a href="{{ route('posts.show', $post) }}" class="absolute bottom-0 right-0 block px-4 py-2 bg-gray-700 text-gray-100 rounded-md self-end justify-self-end hover:bg-gray-800 transition duration-500">Read more</a>
      </div>
       @if ($post->user->is(auth()->user()))
        <x-dropdown>
          <x-slot name="trigger">
           <button>
             <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
               <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
             </svg>
           </button>
          </x-slot>
        <x-slot name="content">
        <x-dropdown-link :href="route('posts.edit', $post)">
            {{ __('Edit') }}
         </x-dropdown-link>
        <form method="POST" action="{{ route('posts.destroy', $post) }}">
          @csrf
          @method('delete')
          <x-dropdown-link :href="route('posts.destroy', $post)" onclick="event.preventDefault(); this.closest('form').submit();">
             {{ __('Delete') }}
          </x-dropdown-link>
        </form>
        </x-slot>
        </x-dropdown>
        @endif
    </div>
    @endforeach
 </div>
</x-app-layout>

resources/views/posts/show.blade.php
<x-app-layout>
  
  <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
    <h1 class="text-gray-700 text-3xl font-bold my-4">{{ $post->title }}</h1>
    <img class="rounded-md" src="{{ url($post->image) }}" alt="{{ $post->title }}"/>
    <p class=" leading-6 text-gray-600 my-4 text-center">{{ $post->post_content }}</p>
  </div>

</x-app-layout>